spring:
  h2:
    console:
      enabled: true
      path: /test_db
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:./h2/test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: 
    password: 
    
logging:
  file:
    path: C:/var/log                                       # log 파일 생성 경로
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} : %30logger{5} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} : %30logger{5} - %msg%n"
  level:
    root: info
    com.hipporing.board: debug